export default defineAppConfig({
  pages: [
    'pages/home/index',
    'pages/order/list/index',
    'pages/order/pal-list/index',
    'pages/order/pool/index',
    'pages/order/place/index',
    'pages/order/detail/index',
    'pages/order/tip/index',
    'pages/report/submit/index',
    'pages/player/detail/index',
    'pages/player/apply/index',
    'pages/finance/withdraw/index',
    'pages/finance/income/index',
    'pages/messages/index',
    'pages/profile/index',
    'pages/order/pal-detail/index',
    'pages/profile/pal/index',
  ],
  tabBar: {
    custom: true,
    color: '#999999',
    selectedColor: '#6190E8',
    backgroundColor: '#ffffff',
    list: [
      { pagePath: 'pages/home/index', text: '首页' },
      { pagePath: 'pages/order/list/index', text: '我的订单' },
      { pagePath: 'pages/messages/index', text: '消息' },
      { pagePath: 'pages/profile/index', text: '我的' },
    ],
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#6190E8',
    navigationBarTitleText: 'SoundX',
    navigationBarTextStyle: 'white',
    navigationStyle: 'custom',
  },
});
